{
"maker": "chrumm 1.0.2",
"quality": {
    "maxChordHeight": 0.01,
    "maxChordAngle": 30,
    "bumpscosity": 50 },
"body": {
    "splitAngle": 12,
    "tiltAngle": -3,
    "alnumTentAngle": 12,
    "thumbTentAngle": 3,
    "pinkyTentAngle": 3,
    "alnumBackAngle": -4.8,
    "alnumFrontAngle": 2.4,
    "thumbFrontAngle": 7.2,
    "minRoofHeight": 8.2,
    "minRidgeWidth": 13.5,
    "relRidgeTaper": 0.25,
    "wallThickness": 4,
    "roofThickness": 4,
    "alnumFrontThickness": 3,
    "outerCornerRadius": 10,
    "outerChamfer": 2,
    "innerChamfer": 1 },
"boss": {
    "diameter": 9.2,
    "innerWallFillet": 3,
    "outerWallMargin": 0.4,
    "countersinkDiameter": 6.4,
    "clearanceHoleDiameter": 4,
    "clearanceHoleLength": 1.3,
    "threadDiameter": 4.2,
    "minThreadLength": 6.5,
    "maxThreadLength": 8,
    "threadRoofMargin": 1.7,
    "threadChamfer": 1 },
"floor": {
    "outerHeight": 3,
    "innerHeight": 1.8,
    "lipHeight": 1.2,
    "lipThickness": 0.87,
    "lipMargin": 0.6,
    "innerChamfer": 1,
    "hexHoles": {
        "minDiameter": 8,
        "maxDiameter": 24,
        "cornerRadius": 1,
        "xOffset": -22,
        "yOffset": -12,
        "holeMargin": 5,
        "wallMargin": 4 }},
"palm": {
    "tentAngle": 3,
    "tiltAngle": 6,
    "taperAngle": 7.2,
    "bodyMargin": 1.5,
    "depth": 80,
    "height": 24,
    "relRoofRoundness": 0.2,
    "roofFillet": 6,
    "floorFillet": 1,
    "floorContactWidth": 15,
    "hitchDepth": 15,
    "hitchScrewPitch": 50,
    "hitchCornerRadius": 5,
    "groove": {
        "width": 10,
        "height": 1.8,
        "roofMargin": 2.5,
        "relClampSize": 0.5 }},
"bumper": {
    "diameter": 8.4,
    "height": 1,
    "margin": 3 },
"layout": {
    "columnPitch": 19,
    "rowPitch": 19,
    "capWidth": 18,
    "capDepth": 18,
    "capTopToPlate": 14,
    "fingerStaggers": [
     [[        0,0 ], [4.8,7.2,4.8,2.4], [2.4,4.8,7.2,4.8], [0,0,0]],
     [[        0,0 ], [4.8,7.2,4.8,2.4], [2.4,4.8,7.2,4.8], [0,0,0]],
     [[        0,0 ], [4.8,7.2,4.8,2.4], [2.4,4.8,7.2,4.8], [0,0,0]],
     [[        0,0 ], [4.8,7.2,4.8,2.4], [2.4,4.8,7.2,4.8], [0,0,0]],
     [[[2.375,0],[]], [[] ,[] ,[] ,[] ], [ [], [], [] ,[]], [0,0,0]] ],
    "thumbUnits":   [[1,1.25,1.25,1.25], [1.25,1.25,1.25,1]],
    "thumbAngles":  [[0,   3,  18,  36], [  36,  18,   3,0]],
    "thumbOffsets": [[0,4.8],                       [0,4.8]] },
"switch": {
    "width": 14.1,
    "depth": 13.9,
    "pinHeight": 3.3,
    "innerHeight": 5,
    "outerMargin": 4,
    "innerMargin": 2,
    "floorMargin": 0.33,
    "entryChamfer": 0.4,
    "clipNotch": {
        "width": 8,
        "depth": 0.9,
        "height": 1.4,
        "taperAngle": 60,
        "isSideways": 0 }},
"encoder": {
    "width": 13.7,
    "depth": 12.8,
    "relPosition": 0.55,
    "holeDiameter": 8,
    "holeHeight": 1.7,
    "holeChamfer": 0.4,
    "pinNotchDepth": 3 },
"support": {
    "baseWidth": 5.2,
    "baseDepth": 2.6,
    "topDepth": 1,
    "sideGap": 0.5,
    "baseGap": 0.2,
    "topGap": 0.2,
    "relBasePosition": 0,
    "relBaseInset": 0.64,
    "relTopInset": 0.83,
    "minOverhangAngle": 30,
    "holeTaperAngle": 45 },
"bracket": {
    "nutSide": "left",
    "nutAcrossFlats": 5.7,
    "counterboreDiameter": 5.9,
    "counterboreLength": 2.7,
    "holeDiameter": 3.3,
    "holeLength": 1.8,
    "cornerRadius": 1.5,
    "taperAngle": 30,
    "taperMargin": 2.1,
    "wallMargin": 0.5,
    "apexMargin": 0.87,
    "baseMargin": 0.2,
    "backCornerExtraMargin": 0.5,
    "frontFloorExtraMargin": 0 },
"cable": {
    "diameter": 4,
    "minBendRadius": 4,
    "ziptieWidth": 3.6,
    "ziptieHeight": 1.8,
    "bracketInset": 0.6,
    "gripHumpWidth": 4.8,
    "gripHumpHeight": 3,
    "wallBumpRadius": 1,
    "wallBumpTaperAngle": 30,
    "wallExitFillet": 1.5 },
"pcb": {
    "thickness": 0.8,
    "mount": {
        "xDistToFirstPinky": 90.9,
        "yDistToFirstPinky": 33.4,
        "bossHeight": 3,
        "bossDiameter": 7.4,
        "threadDiameter": 4,
        "nutDiameter": 6.4 }},
"knob": {
    "outerDiameter": 19.9,
    "outerChamfer": 1.8,
    "roofThickness": 1.2,
    "shaftAcrossFlat": 4.35,
    "shaftDiameter": 6.2,
    "shaftHeight": 7.8,
    "skirtThickness": 2.6,
    "skirtHeight": 4.2,
    "prongDiameter": 0.87,
    "grooveCount": 7,
    "grooveDiameter": 7,
    "grooveInset": 1,
    "grooveCornerRadius": 1 }
}
